import os
from dotenv import load_dotenv
import operator
from typing import Annotated, Sequence, TypedDict, Any

from langchain_core.messages import BaseMessage, HumanMessage, ToolMessage, AIMessage
from langchain_core.tools import tool
from langgraph.graph import StateGraph, END
from langchain_openai import ChatOpenAI 
from openai import OpenAI

import tool_functions

# Load environment variables
load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# This is for LangGraph agent "brain"
LLM = ChatOpenAI(api_key=OPENAI_API_KEY, temperature=0)

# This is for CrystallizationInterpreter
RAW_CLIENT = OpenAI(api_key=OPENAI_API_KEY)

# ==========================================
# 1. Define the State
# ==========================================
class AgentState(TypedDict):
    """
    The state of the agent. 
    'messages' uses `operator.add` to always append new messages to the existing list.
    """
    messages: Annotated[Sequence[BaseMessage], operator.add]
    image_path: str  # Store the image path to be accessible by all nodes
    crystal_signal: str
    precipitate_signal: str
    edge_signal: str
    phase_separation_signal: str
    skin_signal: str
    artifact_signal: str
    clarity_signal: str
    morphology_pattern: str
    ambiguity_flag: bool
    confidence: str
    observation: str

# ==========================================
# 2. Bind Tools
# ==========================================
@tool
def extract_features_from_image_tool(image_path: str) -> str:
    """
    Tool description: 
    Use this tool to extract useful features for protein crystallization screening from a crystal microscope image.
    """
    return tool_functions.extract_features_from_image(image_path, RAW_CLIENT)

bound_llm = LLM.bind_tools([extract_features_from_image_tool])

# Tool registry dictionary
# This allows the graph network to map the LLM's invocation string back to the specific Python function
AVAILABLE_TOOLS = {
    "extract_features_from_image_tool": extract_features_from_image_tool,
}

# ==========================================
# 3. Define Nodes
# ==========================================
def agent_node(state: AgentState) -> dict[str, Any]:
    """
    The 'Brain' node. Calls the Vision Language Model (VLM).
    """
    messages = state["messages"]

    print("🧠 Agent Node: Thinking...")
    
    response = bound_llm.invoke(messages)
    
    if response.tool_calls:
        print(f"🤖 Agent decides to use tools: {response.tool_calls} \n")
    else:   
        print(f"🤖 Agent decides to output: {response.content} \n")
    
    return {"messages": [response]} 

def tool_executor_node(state: AgentState) -> dict[str, Any]:
    """
    The 'Hand' node. Executes tools if requested by the VLM.
    """
    messages = state["messages"]
    last_message = messages[-1]
    image_path = state["image_path"]
    
    print("🛠️ Tool Node: Executing tools...")
    
    tool_messages = []
    
    # A real LLM might call multiple tools in parallel in a single response, so we need to iterate over them
    for tool_call in last_message.tool_calls:
        tool_name = tool_call["name"]
        tool_args = tool_call["args"]
        tool_call_id = tool_call["id"]
        
        print(f"   => Calling tool: {tool_name}, args: {tool_args}")
        
        # Sometimes the model might forget to pass the image path, we can protect against this by falling back to the global state's image_path
        if "image_path" not in tool_args:
             tool_args["image_path"] = image_path
             
        tool_instance = AVAILABLE_TOOLS.get(tool_name)
        if tool_instance:
            try:
                # Execute the corresponding LangChain Tool, passing in arguments
                result = tool_instance.invoke(tool_args)
            except Exception as e:
                result = f"Error executing tool: {e}"
        else:
            result = f"Error: Tool named {tool_name} not found"
            
        print(f"   => Tool result: {result}")
        
        # Core point: The tool execution result **must** be wrapped in a LangChain ToolMessage,
        # and returned with the corresponding tool_call_id. This is the only way to pass the state back to the brain (agent) so it recognizes the relationship.
        tool_messages.append(ToolMessage(
            content=str(result), 
            tool_call_id=tool_call_id
        ))
        
    return {"messages": tool_messages}

# ==========================================
# 4. Define Edge Logic
# ==========================================
def should_continue(state: AgentState) -> str:
    """
    Controls the flow. Checks if the agent wants to use a tool or finish.
    """
    messages = state["messages"]
    last_message = messages[-1]
    
    # Check if the last Message generated by the LLM contains a tool invocation (tool_calls) field
    if hasattr(last_message, 'tool_calls') and last_message.tool_calls:
        # The model wants to use a tool, proceed to Action
        return "continue"
    else:
        # No tool invocation, the model gives the final conclusion, proceed to END
        return "end"

# ==========================================
# 5. Build and Compile the Graph
# ==========================================
def build_image_reasoning_agent():
    # Initialize the graph with our state definition
    workflow = StateGraph(AgentState)

    # Add the nodes we defined
    workflow.add_node("agent", agent_node)
    workflow.add_node("action", tool_executor_node)

    # Set the starting point
    workflow.set_entry_point("agent")

    # Add conditional edge from 'agent' node
    # If should_continue returns "continue", go to "action"
    # If it returns "end", go to the special "END" node
    workflow.add_conditional_edges(
        "agent",
        should_continue,
        {
            "continue": "action",
            "end": END
        }
    )

    # After getting tool results, unconditionally return to the agent to think again
    workflow.add_edge("action", "agent")

    # Compile the state machine into an executable app
    app = workflow.compile()
    return app

# ==========================================
# Example Usage
# ==========================================
if __name__ == "__main__":

    from mwm_vlm.utils.common import save_agent_graph_structure

    SAVE_AGENT_GRAPH_STRUCTURE = False
    AGENT_GRAPH_STRUCTURE_ROOT_PATH = "research/agent_structure_graph"

    agent_app = build_image_reasoning_agent()
    
    if SAVE_AGENT_GRAPH_STRUCTURE:
        # Save the agent graph structure for iterative design
        save_agent_graph_structure(agent_app, AGENT_GRAPH_STRUCTURE_ROOT_PATH)

    # ⚠️ Please ensure there is a real test image at this path, or change it to an existing relative/absolute path
    test_image_path = "/Users/thuang/Documents/Personal/code/image-reasoning-ar26/data/test/25.jpeg" 
    
    # Build your initial prompt, since our tool implements the logic of "using the base model for image classification"
    # We directly let the Agent use the tool to provide the classification result
    initial_prompt = f"The image is located at this local path: '{test_image_path}'. Please use the extract_features_from_image_tool to extract features from it."
    
    # Initialize input state
    initial_state = {
        "messages": [HumanMessage(content=initial_prompt)],
        "image_path": test_image_path
    }
    
    # Start the graph network!
    print("🚀 Starting LangGraph execution...")
    
    # stream() returns the execution process step by step (think -> tool execution -> think -> end)
    for s in agent_app.stream(initial_state):
        print("\n--- Current step state snapshot ---")
        # Print the output of the current node
        for key, value in s.items():
            print(f"Node '{key}':")
